stable:
  replicaCount: 4
  image:
    repository: acrakscanaryprod.azurecr.io/azure-vote-front

canary:
  replicaCount: 1
  image:
    repository: acrakscanaryprod.azurecr.io/azure-vote-front

rbac:
  adminGroupObjectId: "6bafad54-4b72-4bdf-a0f0-ef624315c576"